// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

const { withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs/promises');
const path = require('node:path');

/**
 * Removes `android.permission.INTERNET` from release builds.
 *
 * This is the strongest available proof of the app's central claim. React Native needs
 * the permission in debug, because that is how the Metro bundler reaches the device —
 * but nothing in a release build ever makes a network request, so the permission can be
 * stripped there. Without it, Android does not merely decline to send traffic: the
 * socket calls fail at the OS level, whatever the code or a future dependency tries.
 *
 * A proxy test can only show that no request happened during the run it observed. This
 * shows that none can happen at all, and it is checked in CI.
 *
 * The debug variant is left exactly as Expo generates it, so it keeps both INTERNET
 * and `usesCleartextTraffic` and `npm run android` still reaches Metro.
 */
const RELEASE_MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) 2026 Owais Khan
  Licensed under the Apache License, Version 2.0

  GENERATED by plugins/withOfflineRelease.js — do not edit.

  Every conversion in this app happens on the device. Removing INTERNET from the
  release variant makes that guarantee something the operating system enforces rather
  than something the code promises.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET" tools:node="remove" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove" />
</manifest>
`;


module.exports = function withOfflineRelease(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      // Only the release variant is written. The debug manifest is generated by Expo
      // and carries `usesCleartextTraffic`, without which the Metro connection fails
      // with a CLEARTEXT exception — overwriting it breaks every development build.
      const directory = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'release',
      );
      await fs.mkdir(directory, { recursive: true });
      await fs.writeFile(path.join(directory, 'AndroidManifest.xml'), RELEASE_MANIFEST, 'utf8');

      return modConfig;
    },
  ]);
};
