// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

const { withXcodeProject } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Adds the iOS share extension as a second Xcode target.
 *
 * `ios/` is regenerated by `expo prebuild --clean`, so the target cannot be created once
 * by hand in Xcode — it has to be rebuilt into the project on every prebuild, which is
 * what this does.
 *
 * The extension compiles the engine straight into itself rather than reaching it through
 * a bridge. That is the whole point: a share extension has a hard memory ceiling around
 * 120 MB and must feel instant, so booting a React Native runtime inside one is both slow
 * and a jetsam risk. Because `RasterCodec` and `PdfEngine` are plain Swift, the extension
 * links them and runs no JavaScript at all.
 *
 * `JobQueue.swift` is the one file held back. It keeps a batch alive with
 * `UIApplication.shared.beginBackgroundTask`, and `UIApplication.shared` is unavailable
 * to app extensions — using it is grounds for rejection, not merely a compile error. The
 * extension converts sequentially instead, which is the right shape for it anyway.
 */

const TARGET_NAME = 'ShareExtension';

/** Engine sources the extension compiles. Ordered as they are copied for the app. */
const SHARED_SOURCE_DIRECTORIES = ['generated', 'ConverterCore'];

/**
 * Held back from the extension.
 *
 * `JobQueue` for the reason above; `JobSpec` only because it exists to describe a job for
 * that queue and nothing in the extension submits one.
 */
const APP_ONLY_SOURCES = new Set(['JobQueue.swift', 'JobSpec.swift']);

module.exports = function withShareExtension(config) {
  return withXcodeProject(config, (modConfig) => {
    const project = modConfig.modResults;
    const projectRoot = modConfig.modRequest.projectRoot;
    const platformRoot = modConfig.modRequest.platformProjectRoot;
    const appName = modConfig.modRequest.projectName;
    const appBundleId = config.ios?.bundleIdentifier;

    if (!appName || !appBundleId) {
      throw new Error('withShareExtension: the app name and bundle identifier are required.');
    }

    // Already added on a previous pass through the mod chain.
    if (project.pbxTargetByName(TARGET_NAME)) return modConfig;

    // 1. Copy the extension's own sources next to the app's.
    const source = path.join(projectRoot, 'native', 'ios', TARGET_NAME);
    const destination = path.join(platformRoot, TARGET_NAME);
    fs.rmSync(destination, { recursive: true, force: true });
    fs.mkdirSync(destination, { recursive: true });

    const ownFiles = [];
    for (const entry of fs.readdirSync(source)) {
      fs.copyFileSync(path.join(source, entry), path.join(destination, entry));
      if (entry.endsWith('.swift')) ownFiles.push(entry);
    }

    if (ownFiles.length === 0) {
      throw new Error(`withShareExtension: no Swift sources found in native/ios/${TARGET_NAME}.`);
    }

    // 2. The engine files, referenced where `withConverterCore` already put them so the
    //    two targets compile the same bytes rather than two copies that can drift.
    const shared = [];
    for (const directory of SHARED_SOURCE_DIRECTORIES) {
      const directoryPath = path.join(projectRoot, 'native', 'ios', directory);
      for (const entry of fs.readdirSync(directoryPath)) {
        if (!entry.endsWith('.swift') || APP_ONLY_SOURCES.has(entry)) continue;
        shared.push(path.join(appName, 'ConverterCore', entry));
      }
    }

    // 3. Create the target and its build phases.
    const target = project.addTarget(
      TARGET_NAME,
      'app_extension',
      TARGET_NAME,
      `${appBundleId}.${TARGET_NAME}`,
    );

    project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);
    project.addBuildPhase([], 'PBXFrameworksBuildPhase', 'Frameworks', target.uuid);

    // The project's root group: the one with neither a name nor a path.
    const groups = project.hash.project.objects.PBXGroup;
    const rootGroupKey = Object.keys(groups).find(
      (key) =>
        groups[key].name === undefined &&
        groups[key].path === undefined &&
        Array.isArray(groups[key].children),
    );
    if (!rootGroupKey) {
      throw new Error('withShareExtension: could not find the project root group.');
    }

    // Only the plist goes in as a plain reference. Listing the Swift files here too
    // creates their file references before `addSourceFile` runs, and that call quietly
    // does nothing when the path already exists — the sources end up visible in Xcode's
    // navigator and absent from the Sources build phase, which builds an extension whose
    // principal class is not in its own binary.
    const group = project.addPbxGroup(['Info.plist'], TARGET_NAME, TARGET_NAME);
    project.addToPbxGroup(group.uuid, rootGroupKey);

    // Bare filenames: this group carries the path, and children resolve against it.
    // Prefixing them again asks for `ios/ShareExtension/ShareExtension/…`.
    for (const file of ownFiles) {
      project.addSourceFile(file, { target: target.uuid }, group.uuid);
    }

    /**
     * The engine files are referenced where the app already has them, so the two targets
     * compile the same bytes rather than two copies that can drift.
     *
     * Their group hangs off the project root and carries no path of its own. A group with
     * a path resolves its children against it, which asked the compiler for
     * `ios/ShareExtension/Converter/ConverterCore/RasterCodec.swift` — and passing an
     * undefined path is worse, because it is serialised literally as the folder
     * "undefined".
     */
    const engineGroup = project.addPbxGroup([], 'Engine', '');
    delete groups[engineGroup.uuid].path;
    project.addToPbxGroup(engineGroup.uuid, rootGroupKey);

    for (const file of shared) {
      project.addSourceFile(file, { target: target.uuid }, engineGroup.uuid);
    }

    // 4. Build settings. Everything the template would have set by hand.
    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      if (typeof entry !== 'object' || !entry.buildSettings) continue;
      if (entry.buildSettings.PRODUCT_NAME !== `"${TARGET_NAME}"`) continue;

      Object.assign(entry.buildSettings, {
        INFOPLIST_FILE: `"${TARGET_NAME}/Info.plist"`,
        PRODUCT_BUNDLE_IDENTIFIER: `"${appBundleId}.${TARGET_NAME}"`,
        SWIFT_VERSION: '5.0',
        IPHONEOS_DEPLOYMENT_TARGET: '16.4',
        TARGETED_DEVICE_FAMILY: '"1,2"',
        // An extension ships inside the app, never on its own.
        SKIP_INSTALL: 'YES',
        // The compiler refuses `UIApplication.shared` under this, which is exactly the
        // guard rail wanted: the rule is a review rejection, not just a crash.
        APPLICATION_EXTENSION_API_ONLY: 'YES',
        CLANG_ENABLE_MODULES: 'YES',
        MARKETING_VERSION: '1.0',
        CURRENT_PROJECT_VERSION: '1',
        CODE_SIGN_STYLE: 'Automatic',
      });
    }

    // 5. Embed it in the app.
    //
    // Nothing to do: `addTarget` already created the copy-files phase on the app target
    // with `dstSubfolderSpec = 13` — the PlugIns directory — pointing at this target's
    // own product. Adding a second phase here is what produced "Unexpected duplicate
    // tasks", because Xcode then had two commands copying the same `.appex` to the same
    // place. The target dependency comes with it, so the app cannot build before the
    // extension does.

    return modConfig;
  });
};
