// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

const { withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs/promises');
const path = require('node:path');

/**
 * Strips the permissions that only the development toolchain needs.
 *
 * `INTERNET` is the important one, and the strongest available proof of the app's central
 * claim. React Native needs it in debug, because that is how the Metro bundler reaches the
 * device — but nothing in a release build ever makes a network request, so it can go.
 * Without it Android does not merely decline to send traffic: the socket calls fail at the
 * OS level, whatever the code or a future dependency tries. A proxy test can only show that
 * no request happened during the run it observed; this shows that none can happen at all.
 *
 * The other three arrive from the toolchain rather than from anything this app does, and
 * each was found by dumping the permissions out of a built APK rather than by reading a
 * manifest — the source manifest lists blocked permissions too, complete with their removal
 * markers, so reading it tells you what was *considered*, not what shipped.
 *
 *   SYSTEM_ALERT_WINDOW           react-native, for the development overlay. Users see this
 *                                 one as "Display over other apps", and it is the single
 *                                 most alarming permission a file converter could ask for.
 *   CHANGE_WIFI_MULTICAST_STATE   expo-dev-launcher, for finding a dev server on the local
 *                                 network. On an app whose listing says it never uses the
 *                                 network, this reads as a contradiction — and it is one.
 *   ACCESS_NETWORK_STATE          reachability checks nothing here performs.
 *
 * The debug variant is left exactly as Expo generates it, so it keeps INTERNET and
 * `usesCleartextTraffic` and `npm run android` still reaches Metro.
 */
const RELEASE_MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) 2026 Owais Khan
  Licensed under the Apache License, Version 2.0

  GENERATED by plugins/withOfflineRelease.js — do not edit.

  Every conversion in this app happens on the device. Removing these from the release
  variant makes that guarantee something the operating system enforces rather than
  something the code promises. Each one is here because it appeared in a built APK, not
  because it appeared in a manifest.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools">
    <!-- Metro reaches the device over this in debug. Nothing in release uses it. -->
    <uses-permission android:name="android.permission.INTERNET" tools:node="remove" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove" />
    <!-- react-native's development overlay. Shown to users as "Display over other apps". -->
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:node="remove" />
    <!-- expo-dev-launcher, for discovering a dev server on the local network. -->
    <uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" tools:node="remove" />
</manifest>
`;


module.exports = function withOfflineRelease(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      // Only the release variant is written. The debug manifest is generated by Expo
      // and carries `usesCleartextTraffic`, without which the Metro connection fails
      // with a CLEARTEXT exception — overwriting it breaks every development build.
      const directory = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'release',
      );
      await fs.mkdir(directory, { recursive: true });
      await fs.writeFile(path.join(directory, 'AndroidManifest.xml'), RELEASE_MANIFEST, 'utf8');

      return modConfig;
    },
  ]);
};
