// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

const {
  withDangerousMod,
  withAppBuildGradle,
  withMainApplication,
  withAndroidManifest,
  AndroidConfig,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Adds ConverterCore to the generated Android project.
 *
 * The counterpart to `withConverterCore` on iOS, and for the same reason: `android/` is
 * regenerated by `expo prebuild --clean`, so no hand-written code can live there.
 * Everything real lives under `native/android/` and is copied in and wired up on every
 * prebuild.
 *
 * Everything has to happen here so it cannot drift apart: the sources are copied into
 * the right package directories, the ExifInterface dependency is added, the package is
 * registered with React Native, and the foreground service is declared along with the
 * notification icon and strings it needs.
 */

/** Source directory to Java package. The package must match the `package` line in each file. */
const SOURCE_MAP = [
  ['generated', null], // Tokens.kt and FormatTable.kt declare their own packages
  ['converter', 'com.owaiskhan.converter.core'],
  ['bridge', 'com.owaiskhan.converter.bridge'],
];

/**
 * Every Maven dependency this app adds, and why each one is here.
 *
 * Both are Apache-2.0, which is on the permitted list in docs/DEPENDENCIES.md. The npm
 * licence gate cannot see Maven coordinates, so these are the two that have to be
 * checked by reading rather than by CI — and recorded in NOTICE, which Apache-2.0
 * requires.
 */
const DEPENDENCIES = [
  {
    coordinate: 'androidx.exifinterface:exifinterface:1.4.1',
    reason: 'Reads and writes EXIF across formats, which the platform APIs cannot.',
  },
  {
    // Android exposes no page-level PDF API: PdfRenderer only paints pages into
    // bitmaps and PdfDocument only records canvas drawing, so merging, splitting or
    // reordering with platform APIs alone would repaint every page and destroy its
    // text. PDFBox works on the page objects themselves. The copyleft alternatives —
    // MuPDF, Poppler, Ghostscript — are what most competitors use, and are exactly why
    // most competitors cannot ship under a permissive licence.
    coordinate: 'com.tom-roush:pdfbox-android:2.0.27.0',
    reason: 'Page-level PDF work: merge, split, reorder, and decryption on every API level.',
  },
];

const PACKAGE_IMPORT = 'import com.owaiskhan.converter.bridge.ConverterCorePackage';
const PACKAGE_REGISTRATION = 'add(ConverterCorePackage())';

const SERVICE_NAME = 'com.owaiskhan.converter.core.ConversionService';

/**
 * The MIME types the app will accept from a share sheet or an Open With.
 *
 * `image/*` rather than a list of subtypes: Android matches these literally, and a
 * sending app that labels a HEIC as `image/heic` and one that labels the same file
 * `image/*` would otherwise get different answers. The detector decides what a file
 * actually is once it arrives — an extension is a claim, and so is a MIME type.
 */
const RECEIVED_MIME_TYPES = ['image/*', 'application/pdf'];

/**
 * The three permissions a foreground service costs, and the only ones this app has.
 *
 * The first two are install-time declarations with no dialog. `POST_NOTIFICATIONS` is
 * the single runtime permission the app ever asks for, and it is asked for once, on the
 * first batch long enough to matter. Refusing it does not stop a conversion — Android
 * simply does not display the notification. Nothing here grants access to any data.
 */
const PERMISSIONS = [
  'android.permission.FOREGROUND_SERVICE',
  // Required from API 34, which made every foreground service declare its type.
  'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
  'android.permission.POST_NOTIFICATIONS',
];

/**
 * Pure white, because a notification icon is a mask: Android discards the colour and
 * keeps the alpha. This is the one drawable in the project that cannot come from the
 * design tokens, since it is not a colour the app chooses.
 */
const NOTIFICATION_ICON = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) 2026 Owais Khan
  Licensed under the Apache License, Version 2.0

  GENERATED by plugins/withConverterCoreAndroid.js - do not edit.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M4,7 L13,7 L13,4 L19,8 L13,12 L13,9 L4,9 Z" />
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M20,15 L11,15 L11,12 L5,16 L11,20 L11,17 L20,17 Z" />
</vector>
`;

/** Reads the `package` declaration so a file always lands where its package says. */
function packageOf(source) {
  const match = /^package\s+([\w.]+)/m.exec(source);
  if (!match) throw new Error('withConverterCoreAndroid: a Kotlin file has no package declaration.');
  return match[1];
}

function copySources(projectRoot, platformRoot) {
  const javaRoot = path.join(platformRoot, 'app', 'src', 'main', 'java');
  let copied = 0;

  for (const [directory] of SOURCE_MAP) {
    const source = path.join(projectRoot, 'native', 'android', directory);
    if (!fs.existsSync(source)) {
      throw new Error(
        `withConverterCoreAndroid: native/android/${directory} is missing. ` +
          'Run `npm run generate` if the generated sources have not been produced yet.',
      );
    }

    for (const entry of fs.readdirSync(source)) {
      if (!entry.endsWith('.kt')) continue;
      const contents = fs.readFileSync(path.join(source, entry), 'utf8');
      const destination = path.join(javaRoot, ...packageOf(contents).split('.'));
      fs.mkdirSync(destination, { recursive: true });
      fs.writeFileSync(path.join(destination, entry), contents, 'utf8');
      copied += 1;
    }
  }

  if (copied === 0) {
    throw new Error('withConverterCoreAndroid: no Kotlin sources were found to copy.');
  }
}

function writeNotificationIcon(platformRoot) {
  const directory = path.join(platformRoot, 'app', 'src', 'main', 'res', 'drawable');
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'ic_stat_converter.xml'), NOTIFICATION_ICON, 'utf8');
}

module.exports = function withConverterCoreAndroid(config) {
  // 1. Copy the sources into their package directories, and the notification icon
  //    the foreground service draws with.
  config = withDangerousMod(config, [
    'android',
    (modConfig) => {
      copySources(modConfig.modRequest.projectRoot, modConfig.modRequest.platformProjectRoot);
      writeNotificationIcon(modConfig.modRequest.platformProjectRoot);
      return modConfig;
    },
  ]);

  // 2. Add the Maven dependencies.
  config = withAppBuildGradle(config, (modConfig) => {
    const missing = DEPENDENCIES.filter(
      (entry) => !modConfig.modResults.contents.includes(entry.coordinate),
    );
    if (missing.length === 0) return modConfig;

    const block = missing
      .map((entry) => `\n    // ${entry.reason}\n    implementation("${entry.coordinate}")`)
      .join('');

    modConfig.modResults.contents = modConfig.modResults.contents.replace(
      /dependencies\s*\{/,
      (match) => `${match}${block}\n`,
    );
    return modConfig;
  });

  // 3. Declare the foreground service and the permissions it needs.
  config = withAndroidManifest(config, (modConfig) => {
    const manifest = modConfig.modResults;

    for (const permission of PERMISSIONS) {
      AndroidConfig.Permissions.ensurePermission(manifest, permission);
    }

    // Share and Open With. Added to the launcher activity rather than a separate one,
    // so a share lands in the app the user already knows rather than a stub that then
    // has to hand over.
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(manifest);
    activity['intent-filter'] = activity['intent-filter'] ?? [];

    const filters = [
      // One file shared.
      ...RECEIVED_MIME_TYPES.map((mimeType) => ({
        action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
        category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
        data: [{ $: { 'android:mimeType': mimeType } }],
      })),
      // Several at once — the case a batch converter exists for.
      ...RECEIVED_MIME_TYPES.map((mimeType) => ({
        action: [{ $: { 'android:name': 'android.intent.action.SEND_MULTIPLE' } }],
        category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
        data: [{ $: { 'android:mimeType': mimeType } }],
      })),
      // Open With, from a file manager or another app's document view.
      ...RECEIVED_MIME_TYPES.map((mimeType) => ({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
        category: [
          { $: { 'android:name': 'android.intent.category.DEFAULT' } },
          { $: { 'android:name': 'android.intent.category.BROWSABLE' } },
        ],
        data: [
          { $: { 'android:scheme': 'content', 'android:mimeType': mimeType } },
          { $: { 'android:scheme': 'file', 'android:mimeType': mimeType } },
        ],
      })),
    ];

    for (const filter of filters) {
      const already = activity['intent-filter'].some(
        (existing) =>
          existing.action?.[0]?.$['android:name'] === filter.action[0].$['android:name'] &&
          existing.data?.[0]?.$['android:mimeType'] === filter.data[0].$['android:mimeType'],
      );
      if (!already) activity['intent-filter'].push(filter);
    }

    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
    application.service = application.service ?? [];

    if (!application.service.some((entry) => entry.$['android:name'] === SERVICE_NAME)) {
      application.service.push({
        $: {
          'android:name': SERVICE_NAME,
          // Nothing outside this app has any reason to start it.
          'android:exported': 'false',
          // Android's category for on-device file processing.
          'android:foregroundServiceType': 'dataSync',
          // Left false so the service receives `onTaskRemoved` and can cancel the batch
          // itself. Letting the system stop it silently would leave the queue converting
          // with no notification and no UI, which is the one outcome worth avoiding.
          'android:stopWithTask': 'false',
        },
      });
    }

    return modConfig;
  });

  // 4. Register the package. Expo's template leaves a marked spot for exactly this.
  return withMainApplication(config, (modConfig) => {
    let contents = modConfig.modResults.contents;

    if (!contents.includes(PACKAGE_IMPORT)) {
      contents = contents.replace(
        /^import com\.facebook\.react\.PackageList$/m,
        (match) => `${match}\n${PACKAGE_IMPORT}`,
      );
    }

    if (!contents.includes(PACKAGE_REGISTRATION)) {
      const anchor = 'PackageList(this).packages.apply {';
      if (!contents.includes(anchor)) {
        throw new Error(
          'withConverterCoreAndroid: could not find the package list in MainApplication.kt. ' +
            'The Expo template changed; update this plugin.',
        );
      }
      contents = contents.replace(
        anchor,
        `${anchor}\n          // ConverterCore's TurboModules are app-local, so they are not autolinked.\n          ${PACKAGE_REGISTRATION}`,
      );
    }

    modConfig.modResults.contents = contents;
    return modConfig;
  });
};
