// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

const {
  withDangerousMod,
  withAppBuildGradle,
  withMainApplication,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Adds ConverterCore to the generated Android project.
 *
 * The counterpart to `withConverterCore` on iOS, and for the same reason: `android/` is
 * regenerated by `expo prebuild --clean`, so no hand-written code can live there.
 * Everything real lives under `native/android/` and is copied in and wired up on every
 * prebuild.
 *
 * Three things have to happen, and all three are done here so they cannot drift apart:
 * the sources are copied into the right package directories, the ExifInterface
 * dependency is added, and the package is registered with React Native.
 */

/** Source directory to Java package. The package must match the `package` line in each file. */
const SOURCE_MAP = [
  ['generated', null], // Tokens.kt and FormatTable.kt declare their own packages
  ['converter', 'com.owaiskhan.converter.core'],
  ['bridge', 'com.owaiskhan.converter.bridge'],
];

/** Apache-2.0, and the only way to read and write EXIF reliably across formats. */
const EXIF_DEPENDENCY = 'androidx.exifinterface:exifinterface:1.4.1';

const PACKAGE_IMPORT = 'import com.owaiskhan.converter.bridge.ConverterCorePackage';
const PACKAGE_REGISTRATION = 'add(ConverterCorePackage())';

/** Reads the `package` declaration so a file always lands where its package says. */
function packageOf(source) {
  const match = /^package\s+([\w.]+)/m.exec(source);
  if (!match) throw new Error('withConverterCoreAndroid: a Kotlin file has no package declaration.');
  return match[1];
}

function copySources(projectRoot, platformRoot) {
  const javaRoot = path.join(platformRoot, 'app', 'src', 'main', 'java');
  let copied = 0;

  for (const [directory] of SOURCE_MAP) {
    const source = path.join(projectRoot, 'native', 'android', directory);
    if (!fs.existsSync(source)) {
      throw new Error(
        `withConverterCoreAndroid: native/android/${directory} is missing. ` +
          'Run `npm run generate` if the generated sources have not been produced yet.',
      );
    }

    for (const entry of fs.readdirSync(source)) {
      if (!entry.endsWith('.kt')) continue;
      const contents = fs.readFileSync(path.join(source, entry), 'utf8');
      const destination = path.join(javaRoot, ...packageOf(contents).split('.'));
      fs.mkdirSync(destination, { recursive: true });
      fs.writeFileSync(path.join(destination, entry), contents, 'utf8');
      copied += 1;
    }
  }

  if (copied === 0) {
    throw new Error('withConverterCoreAndroid: no Kotlin sources were found to copy.');
  }
}

module.exports = function withConverterCoreAndroid(config) {
  // 1. Copy the sources into their package directories.
  config = withDangerousMod(config, [
    'android',
    (modConfig) => {
      copySources(modConfig.modRequest.projectRoot, modConfig.modRequest.platformProjectRoot);
      return modConfig;
    },
  ]);

  // 2. Add the ExifInterface dependency.
  config = withAppBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.contents.includes(EXIF_DEPENDENCY)) return modConfig;

    modConfig.modResults.contents = modConfig.modResults.contents.replace(
      /dependencies\s*\{/,
      (match) =>
        `${match}\n    // Reads and writes EXIF across formats, which the platform APIs cannot.\n` +
        `    implementation("${EXIF_DEPENDENCY}")\n`,
    );
    return modConfig;
  });

  // 3. Register the package. Expo's template leaves a marked spot for exactly this.
  return withMainApplication(config, (modConfig) => {
    let contents = modConfig.modResults.contents;

    if (!contents.includes(PACKAGE_IMPORT)) {
      contents = contents.replace(
        /^import com\.facebook\.react\.PackageList$/m,
        (match) => `${match}\n${PACKAGE_IMPORT}`,
      );
    }

    if (!contents.includes(PACKAGE_REGISTRATION)) {
      const anchor = 'PackageList(this).packages.apply {';
      if (!contents.includes(anchor)) {
        throw new Error(
          'withConverterCoreAndroid: could not find the package list in MainApplication.kt. ' +
            'The Expo template changed; update this plugin.',
        );
      }
      contents = contents.replace(
        anchor,
        `${anchor}\n          // ConverterCore's TurboModules are app-local, so they are not autolinked.\n          ${PACKAGE_REGISTRATION}`,
      );
    }

    modConfig.modResults.contents = contents;
    return modConfig;
  });
};
