// Copyright (c) 2026 Owais Khan
// Licensed under the Apache License, Version 2.0

import { useMemo } from 'react';
import { SectionList, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

import { Button, Card, Screen, SectionLabel, Text } from '@/components';
import inventory from '@/generated/licenses.json';
import { useTheme } from '@/theme';
import type { RootStackParamList } from '@/navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'Licenses'>;

type Entry = { name: string; version: string; license: string };

/**
 * Every third-party licence, in the binary rather than only in the repository.
 *
 * This exists because Apache 2.0 section 4(d) asks for the NOTICE to be conveyed with the
 * distribution, and the Open Font Licence asks the same of the font's terms. A LICENSES.md
 * sitting in a Git repository does not reach the person who installed the app from a store,
 * and for a long time both NOTICE and LICENSES.md told that person to look for this screen,
 * which did not exist.
 *
 * The list is generated by `npm run license:report` from the same pass that writes
 * LICENSES.md, so the inventory a user can read and the inventory in the repository come
 * from one source and cannot drift apart.
 */
export function LicensesScreen({ navigation }: Props) {
  const { t } = useTranslation();
  const theme = useTheme();

  const sections = useMemo(
    () => [
      { key: 'packages', title: t('licenses.packages'), data: inventory.packages as Entry[] },
      { key: 'native', title: t('licenses.native'), data: inventory.native as Entry[] },
    ],
    [t],
  );

  return (
    <Screen>
      <Text variant="h1">{t('licenses.title')}</Text>
      <Text variant="bodySm" color="textSecondary" style={{ marginTop: theme.space.xs }}>
        {t('licenses.subtitle', {
          count: inventory.packages.length + inventory.native.length,
        })}
      </Text>

      <Card style={{ marginTop: theme.space.lg }}>
        <Text variant="bodySm" color="textSecondary">
          {t('licenses.appNotice')}
        </Text>
      </Card>

      <SectionList
        style={{ flex: 1, marginTop: theme.space.lg }}
        contentContainerStyle={{ paddingBottom: theme.space.xl }}
        showsVerticalScrollIndicator={false}
        sections={sections}
        keyExtractor={(item, index) => `${item.name}-${index}`}
        // The list is long and every row is the same height, so this keeps scrolling
        // smooth on the oldest device the app supports.
        initialNumToRender={24}
        renderSectionHeader={({ section }) => (
          <View style={{ backgroundColor: theme.color.bgCanvas, paddingVertical: theme.space.sm }}>
            <SectionLabel>{section.title}</SectionLabel>
          </View>
        )}
        renderItem={({ item }) => (
          <View
            accessible
            accessibilityLabel={t('a11y.labelledDetail', {
              label: item.name,
              detail: t('licenses.entry', { version: item.version, license: item.license }),
            })}
            style={[
              styles.row,
              {
                paddingVertical: theme.space.sm,
                borderBottomWidth: StyleSheet.hairlineWidth * 2,
                borderBottomColor: theme.color.borderHairline,
              },
            ]}
          >
            <Text
              variant="bodySm"
              numberOfLines={1}
              accessibilityElementsHidden
              importantForAccessibility="no"
              style={styles.name}
            >
              {item.name}
            </Text>
            <Text
              variant="caption"
              color="textTertiary"
              accessibilityElementsHidden
              importantForAccessibility="no"
            >
              {t('licenses.entry', { version: item.version, license: item.license })}
            </Text>
          </View>
        )}
      />

      <View style={{ paddingTop: theme.space.md }}>
        <Button label={t('common.done')} variant="ghost" onPress={() => navigation.goBack()} />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  name: { flex: 1, minWidth: 0 },
});

/** Exported for the test that asserts the inventory is not empty and is well shaped. */
export const licenseInventory = inventory;
